[project]
name = "homework"
version = "1.0.0"
description = "ML Zoomcamp Module 5 - Lead Scoring Deployment"
requires-python = ">=3.12"
dependencies = [
    "scikit-learn==1.6.1",
    "fastapi==0.120.2",
    "uvicorn==0.38.0",
    "pydantic==2.12.3",
    "requests==2.31.0",
]
